version: "3.4"

networks:
  eqd-network:
    driver: bridge

services:
  database:
    container_name: eqd-database
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 21433:1433
    environment:
      SA_PASSWORD: "Str0ngPass!"
      ACCEPT_EULA: "Y"
    networks:
      - eqd-network

  api:
    container_name: eqd-api
    image: eqd/api
    restart: always
    depends_on:
      - database
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_HTTPS_PORT: 5001
      ConnectionStrings:DefaultConnection: Server=database; Database=ef-demo; User Id=sa; Password=Str0ngPass!;
    ports:
      - 5001:5001
    networks:
      - eqd-network
    volumes:
      - ~/.aspnet/https:/https:ro
