version: "3.4"

networks:
  eqd-network:
    driver: bridge

services:
  database:
    container_name: eqd-database
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: pi
      POSTGRES_PASSWORD: Str0ngPass!
      POSTGRES_DB: db
      POSTGRES_ADMIN_PASSWORD: Str0ngPass!
    ports:
      - 5432:5432
    networks:
      - eqd-network

  api:
    container_name: eqd-api
    image: eqd/api
    restart: always
    depends_on:
      - database
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_Kestrel__Certificates__Default__Password: password
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+:5001
      ASPNETCORE_HTTPS_PORT: 5001
      ConnectionStrings:DefaultConnection: Host=database;Database=db;User Id=pi;Password=Str0ngPass!
    ports:
      - 5001:5001
    networks:
      - eqd-network
    volumes:
      - ~/.aspnet/https:/https:ro
